jabardigitalservice/pikobar-rapidtest-backoffice

- assets/app.scss
- components/EventForm.vue
- components/EventView.vue
- components/EventsDatatable.vue
- components/global/PkbrInput.vue
- components/global/PkbrInputDate.vue
- components/global/PkbrInputTime.vue
- components/global/PkbrSelect.vue
- layouts/default.vue
- nuxt.config.js
- package-lock.json
- package.json
- pages/events/_eventId/edit.vue
- pages/events/_eventId/index.vue
- pages/events/create.vue
- pages/events/index.vue
- plugins/alert.js
- plugins/global-components.js
- plugins/toast.js
- plugins/validation.js
- store/alert.js
- store/area.js
- store/events.js
- store/toast.js
- utilities/constant.js
- utilities/formater.js
Penambahan Component yang sangat sering digunakan.
Initial commit untuk flow Events.
> Events pages & Global components

- pages/events/_eventId/add.vue
- store/eventParticipants.js
- store/events.js
> Fix error message toast wording

- assets/app.scss
- components/ApplicantsDatatable.vue
- components/ApplicantsDatatableClient.vue
- components/EventView.vue
- components/EventsApplicants.vue
- components/EventsApplicantsClient.vue
- components/EventsDatatable.vue
- layouts/default.vue
- pages/candidates/index.vue
- pages/events/_eventId/add.vue
- pages/events/_eventId/index.vue
- pages/participants/index.vue
- store/applicants.js
- store/eventParticipants.js
- store/events.js
> 07-10/08/2020

- components/ApplicantViewDialog.vue
- utilities/constant.js
Redesign detail peserta dan calon peserta tes masif
https://trello.com/c/SAbCMQqn/144-improvement-detail-daftar-peserta
> Detail applicant

- components/ApplicantsDatatable.vue
- components/global/PkbrSelect.vue
- pages/candidates/index.vue
- pages/participants/index.vue
- store/applicants.js
- utilities/constant.js
Update filter pada daftar peserta dan calon peserta:
- Menambahkan filter tanggal
- Menambahkan filter status kesehatan
- Menambahkan button cari
- Menambahkan button reset
https://trello.com/c/7mWhUxDV/158-calon-peserta-dan-daftar-peserta-tambahan-filter-di-dalam-calon-peserta-dan-daftar-peserta
> Filter applicant

- components/EventApplicantUncheckDialog.vue
- components/EventApplicantUncheckWarningDialog.vue
- components/EventsApplicants.vue
- store/eventParticipants.js
- utilities/constant.js
Uncheck data peserta:
1. Admin klik tombol uncheck di dalam detail kegiatan
2. Muncul pop up yang memberitahukan admin akan menguncheck peserta itu
3. Ketika setuju, data check in, kode sample, dan lokasi kegiatan akan hilang dari peserta itu
https://trello.com/c/hbP88FCT/159-detail-kegiatan-admin-bisa-menguncheck-peserta-yang-sudah-check-in-tapi-tidak-mengikuti-tes
> Uncheck applicant

- components/ApplicantsDatatable.vue
- pages/events/_eventId/add.vue
Preview:
- Memperbaiki bug filter saat mounted
- Memperbaiki bug dihalaman event tambah peserta
https://trello.com/c/7mWhUxDV/158-calon-peserta-dan-daftar-peserta-tambahan-filter-di-dalam-calon-peserta-dan-daftar-peserta
> Applicant: fix filter mounted

- components/ApplicantViewDialog.vue
Preview:
bug fix detail peserta double data gejala dan penyakit bawaan.
https://trello.com/c/oWbPZF80/175-bug-detail-calon-peserta-daftar-peserta
> Applicant: fixing detail applicant

- components/ApplicantsDatatable.vue
- pages/candidates/index.vue
- pages/participants/index.vue
Preview:
Menambahkan filter sessionId
> Filter sessionId

- components/ApplicantsDatatable.vue
- components/DialogIntegratingData.vue
- components/EventsApplicants.vue
- store/eventParticipants.js
- utilities/constant.js
Preview:
Integrasi data tes masif ke manlab
https://trello.com/c/EVttHkAw/131-kegiatan-admin-bisa-mengirim-data-peserta-yang-hadir-di-kegiatan-ke-manajemen-labkesda
> Integrating data labkes

- components/ApplicantsDatatable.vue
preview:
menambahkan filter reset sessionId
> filter: reset sessionId

- pages/events/_eventId/add.vue
Menampilkan data peserta dengan status "new" di halaman tambah peserta
> Add participant

- components/DialogIntegratingData.vue
- components/EventsApplicants.vue
- store/eventParticipants.js
Preview:
- Menambahkan response sukses integrasi manlab
- Menampilkan data yang akan di integrasi ke user berdasarkan data checkin
> IntegrationManlab: handling success message

- components/EventsApplicants.vue
Preview:
Update list participant ketika integrasi berhasil
> IntegrationManlab: getList participants when success integration

- components/ApplicantsDatatable.vue
- pages/events/_eventId/add.vue
Preview:
1. Menambahkan kolom status kesehatan di daftar peserta dan calon peserta
2. Get list peserta semua status di tambah peserta
> Contact tracing

- components/ApplicantsDatatable.vue
- pages/events/_eventId/add.vue
- store/applicants.js
Preview:
- Menambahkan parameter eventId
https://trello.com/c/4zHlH2aW/215-bug-tambah-peserta-pada-kegiatan
> AddParticipant: added param eventId

- components/ApplicantsDatatable.vue
Preview:
Mengganti tanggal terdaftar dengan updated_at
https://trello.com/c/2nnkSoHJ/220-data-yang-muncul-di-calon-peserta-dan-daftar-peserta-adalah-updatedat
> ListParticipant: change tanggal terdaftar with updated_at

- components/EventForm.vue
> Hotfix: set hostname null

- components/EventsApplicants.vue
- layouts/default.vue
- store/eventParticipants.js
Preview:
- Custom error message integration SIM Lab
Related: 
https://trello.com/c/xMp7UHJd/204-catatan-ux-pengiriman-data-ke-labkesda
> Bug fix integration

- components/DialogIntegratingData.vue
- components/EventsApplicants.vue
Preview:
Merubah redaksi popup integrasi SIM Lab.
Related:
https://trello.com/c/xMp7UHJd/204-catatan-ux-pengiriman-data-ke-labkesda
> BugFixRedactionIntegration: change redaction dialog

- components/EventForm.vue
- components/EventView.vue
- components/EventsDatatable.vue
Preview:
- Ketika edit data penyelenggara tidak hilang
Related:
https://trello.com/c/GyftoNmf/241-bug-edit-kegiatan
> Edit event

- components/EventForm.vue
- components/EventView.vue
Preview:
- Bug fix detail kegiatan registration type
- Bug fix edit kegiatan registration type
https://trello.com/c/Zvnx3H1l/247-kegiatan-ketika-user-mau-membuat-kegiatan-dia-ada-pilihan-apakah-kegiatan-itu-untuk-daftar-mandiri-atau-rujukan
https://trello.com/c/GyftoNmf/241-bug-edit-kegiatan
> Detail event

- components/ApplicantsDatatable.vue
- components/EventsApplicants.vue
- store/applicants.js
Preview:
- Change updated_at to registration_at
Related:
https://trello.com/c/PKQCyuXD/229-registrationat-di-calon-peserta-dan-daftar-peserta
> Add registration at

- components/EventsApplicants.vue
Preview:
- Mengubah label `Status terkirim` menjadi `Data terkirim ke SIM Lab`
- Mengubah label `Tanggal Terkirim ke Manlab` menjadi `Tanggal Terkirim ke SIM Lab`
Related:
https://trello.com/c/ktuVnBqF/258-ganti-nama-label-status-terkirim-menjadi-data-terkirim-ke-sim-lab
> ChangeLabel: change label 'status terkirim'

- components/EventView.vue
Preview:
- Mengganti label hasil tes menjadi kirim hasil tes
Related: https://trello.com/c/6B2wz7hE/259-hasil-tes-diganti-menjadi-kirim-hasil-tes
> DetailEvent: added applicant_notified_result_count

- store/applicants.js
Preview:
- Bug fix sorting desc and asc in applicant
Related: https://trello.com/c/PKQCyuXD/229-registrationat-di-calon-peserta-dan-daftar-peserta
> ApplicantSorting: bug fix sorting applicant

- components/EventsApplicants.vue
Preview: 
- Remove selected applicant
Related:
https://trello.com/c/6B2wz7hE/259-hasil-tes-diganti-menjadi-kirim-hasil-tes
> UpdateDataListEvent: remove selected applicant

- layouts/default.vue
- nuxt.config.js
- package.json
- pages/index.vue
Preview:
- Mengganti nama project `Tes Masif` menjadi `Pikobar Pendaftaran Tes COVID-19`
Related:
https://trello.com/c/8xUqjsZO/268-menghilangkan-kata-tes-masif-di-pendaftaran
> ChangeTesMasif: change project name

- components/DialogIntegratingData.vue
Preview:
- Mengubah kalimat di popup integrasi data SIM Lab
Related:
https://trello.com/c/Lfttdrge/270-tambahkan-wording-pastikan-data-yang-dikirim-sudah-benar-data-yang-sudah-dikirim-tidak-dapat-dirubah-dihapus-atau-dikirim-lagi-d
> ChangeWording: change wordin in popup integration data

- components/DialogIntegratingData.vue
Preview:
- Mengubah warna pada warning text
- Menampilkan pagination footer pada table popup integrasi
Related:
https://trello.com/c/a1LwZY6u/271-bug-preview-peserta-saat-integrasi-simlab
> PopupTableIntegration: show footer tabel and change color text

- components/EventsApplicants.vue
Preview:
- Menyesuaikan export untuk f1 dan f2
Related:
https://trello.com/c/XB4yayaZ/263-ekspor-f2-di-kegiatan
> ExportF2: adjusment export f1 and f2

- components/ApplicantEditDialog.vue
- components/EventsApplicants.vue
Preview:
- Mengubah kode sample menjadi button
- Menambahkan edit peserta di detail kegiatan
Related:
https://trello.com/c/XxjLimdT/278-detail-kegiatan-perubahan-edit-kode-sample-nama-jenis-kelamin-dan-instansi-pekerjaan
> CodeSample: edit code sample and edit applicant

- components/DialogIntegratingData.vue
- components/DialogIntegrationWarning.vue
Preview:
- Menambahkan warning berupa pop up ketika integrasi 
Related:
https://trello.com/c/Lfttdrge/270-tambahkan-wording-pastikan-data-yang-dikirim-sudah-benar-data-yang-sudah-dikirim-tidak-dapat-dirubah-dihapus-atau-dikirim-lagi-d
> WarningIntegration: added dialog warning integration SIM Lab

- components/DialogIntegratingData.vue
- components/EventsApplicants.vue
Preview:
- Memperbaiki tabel preview integrasi SIM Lab
- Menampilkan semua data yang akan diintegrasikan ke SIM Lab
Related:
https://trello.com/c/a1LwZY6u/271-bug-preview-peserta-saat-integrasi-simlab
> Table preview

- components/ApplicantEditDialog.vue
Preview:
- Refactor edit applicant
Related:
https://trello.com/c/I2p41uK6/273-calon-peserta-daftar-peserta-edit-data-peserta
> Edit applicant

- components/EventsDatatable.vue
- pages/events/index.vue
- store/events.js
Preview:
- Menambahkan filter kabkota di tabel list kegiatan
Related:
https://trello.com/c/OX85GsQw/279-list-kegiatan-adanya-filter-kegiatan-based-on-kota-kabupaten-di-list-kegiatan
> FilterEvent: added filter city code

- components/EventsApplicants.vue
- store/blastNotif.js
Refer to task --> https://trello.com/c/Fyfou9pX/284-bug-anomaly-kirim-hasil-test
Overview:
- Fixing errors above, when click button 'Kirim Hasil Test' and no ones selected
- Fixing toast success when process was error
Note:
- Tested on local
cc: mas @yohang88
> fixing bug toast on send result test

- components/EventsDatatable.vue
- pages/events/index.vue
- store/events.js
Preview:
- Menambahkan filter tanggal mulai dan tanggal berakhir
Related:
https://trello.com/c/u9xpaSTh/282-list-kegiatan-filter-kegiatan-berdasarkan-tanggal-pelaksanaannya
> FilterEvent: added filter by start_date and end_date in list event

- components/EventsApplicants.vue
- components/EventsDatatable.vue
- pages/events/_eventId/index.vue
Preview:
- Menambahkan button search and reset pada list event
- Menambahkan button search and reset pada detail event participants
Related:
https://trello.com/c/FHLyZEp0/283-detail-kegiatan-filter-tanggal-peserta-checkin-di-detail-kegiatan
https://trello.com/c/u9xpaSTh/282-list-kegiatan-filter-kegiatan-berdasarkan-tanggal-pelaksanaannya
> Filter detail event

- components/EventsApplicants.vue
- components/EventsDatatable.vue
- store/eventParticipants.js
Preview:
- Bug fix filter list event
- Bug fix filter detail event
- Change button color in detail event page
Related:
https://trello.com/c/u9xpaSTh/282-list-kegiatan-filter-kegiatan-berdasarkan-tanggal-pelaksanaannya
https://trello.com/c/FHLyZEp0/283-detail-kegiatan-filter-tanggal-peserta-checkin-di-detail-kegiatan
> Bug fix filter

- components/EventsApplicants.vue
- components/EventsDatatable.vue
Preview:
- Reset filter ketika data di mounted
Related:
https://trello.com/c/FHLyZEp0/283-detail-kegiatan-filter-tanggal-peserta-checkin-di-detail-kegiatan
> resetFilter: call reset filter when mounted

- components/EventsApplicants.vue
- components/EventsDatatable.vue
- pages/events/_eventId/index.vue
- pages/events/index.vue
- store/blastNotif.js
- store/eventParticipants.js
- store/events.js
Deploy to Prod:
- Improve filter kegiatan
- Improve filter detail kegiatan
> Deploy to Prod

- assets/app.scss
- components/EventImportTestResultDialog.vue
Preview:
- Redesign popup import hasil test
- Menambahkan template import hasil test
Related:
- https://trello.com/c/buJN5tYQ/280-adanya-template-yg-bisa-didownload-buat-import-hasil-tes
> Import test result

- components/EventView.vue
Preview:
- Bug fix issue event view
- Refactor page event view
> BugFixEventView: bug fix sentry issue and refactor event view

- components/EventImportTestResultDialog.vue
Preview: 
- Menambahkan efek persistent pada popup 
Related:
https://trello.com/c/buJN5tYQ/280-adanya-template-yg-bisa-didownload-buat-import-hasil-tes
> bugFixImport: added persistent popup

- assets/app.scss
- components/ApplicantViewDialog.vue
- components/ApplicantsDatatable.vue
- components/DialogWarningTestResult.vue
- components/EventImportTestResultDialog.vue
- components/EventView.vue
- components/EventsApplicants.vue
- components/EventsDatatable.vue
- layouts/default.vue
- pages/login.vue
- utilities/formater.js
Preview:
- Redesign event detail
- Redesign table applicant
- Redesign table event
- Solving code smell
Related:
https://trello.com/c/9n0SbLGV/167-redesign-halaman-detail-kegiatan
> Redesign detail event

- components/EventImportTestResultDialog.vue
- components/EventsApplicants.vue
- store/eventParticipants.js
Preview:
- added validation import
Related:
https://trello.com/c/J0rsD5LQ/289-validasi-import-hasil-tes
> Import validation

- components/EventsApplicants.vue
Preview:
- Fixing button margin
- Fixing tooltip
Related:
https://trello.com/c/9n0SbLGV/167-redesign-halaman-detail-kegiatan
> bugFixRedesign: fixing tooltip and added margin button

- assets/app.scss
- components/ApplicantViewDialog.vue
- components/ApplicantsDatatable.vue
- components/DialogWarningTestResult.vue
- components/EventImportTestResultDialog.vue
- components/EventView.vue
- components/EventsApplicants.vue
- components/EventsDatatable.vue
- layouts/default.vue
- pages/login.vue
- store/eventParticipants.js
- utilities/formater.js
Preview:
- Redesign detail event
- Validation import
> Deploy to production

- nuxt.config.js
Preview:
- Fixing setup sentry performance
> fixingSentry: fixing sentry performance

- components/DialogIntegratingData.vue
- components/EventsApplicants.vue
- utilities/formater.js
Preview:
* Fixing button integration warning
* Fixing bug sentry
* refactor fixing bug sentry "split"
> Deploy to Prod: Fixing button integration (#138)

- components/ApplicantViewDialog.vue
- utilities/constant.js
Preview:
- Added new status person
Related: 
https://app.clickup.com/t/26g48my
Evidence
title: Added status person
project: Pikobar Pengujian
participants: @maruf12, @maulanayuseph, @naufalihsank, @bangunbagustapa, @yoslie
> added new status person
